"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { supabase, errorMessage, configured } from "@/lib/supabase";
export default function BusinessLogin() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [mode,setMode]=useState<"login"|"signup">("signup"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try {
    const client=supabase();
    if(mode==="signup") { const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback?next=/business/new`}});if(error)throw error; if(data.session) location.assign("/business/new"); else setMessage("Compte créé. Confirmez votre adresse avec le lien reçu par email, puis configurez votre commerce."); }
    else { const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;location.assign("/business"); }
  } catch(error){setMessage(errorMessage(error));}finally{setBusy(false);}};
  return <div className="auth-split"><aside className="auth-side"><h2>Fidélisez vos clients dès aujourd’hui.</h2><ul><li><b>✓</b>30 jours d’essai gratuit, sans carte bancaire</li><li><b>✓</b>Aucune application pour vos clients : un QR code suffit</li><li><b>✓</b>Espace caisse : gérez vos caissiers et suivez leurs résultats</li><li><b>✓</b>Données protégées, résiliation en un clic</li></ul><div className="auth-plans">À partir de <b>9 € HT / mois</b> · Essentiel, Pro et Multi-boutiques</div></aside><div className="auth-main"><div className="auth-card"><span className="kicker">ESPACE COMMERÇANT</span><h1>{mode==="login"?"Connexion":"Créer mon compte"}</h1><p>Votre établissement, vos clients, votre programme.</p>{!configured?<p role="alert">Configurez Supabase avant de créer un compte.</p>:<form onSubmit={submit}><label>Email professionnel<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mot de passe<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="login"?"current-password":"new-password"}/></label><button className="button dark" disabled={busy}>{mode==="login"?"Se connecter":"Créer mon compte"}</button></form>}{message&&<p role="status">{message}</p>}<button className="text-switch" type="button" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("");}}>{mode==="login"?"Nouveau commerçant ? Créer un compte":"Déjà inscrit ? Se connecter"}</button><p><Link href="/privacy">Confidentialité et données personnelles</Link></p></div></div></div>;
